### ISSUE TITLE
Error in Geo Request

### ISSUE THREAD

**Issue by retep-mathwizard** [rubenvereecken/pokemongo-api#102]

**Comment by retep-mathwizard** [comment]
```
     util.setupLogger()
    logging.debug('Logger set up')
    password = "password"
    username = "username@gmail.com"
    auth = "google"
    location = "301 Caldwell Ln Davidson, NC"
    encrypt_lib = "libencrypt-osx-64.so"
    auth_session = PokeAuthSession(
        username,
        password,
        auth,
        location,
        encrypt_lib,
    )   
    session = auth_session.authenticate(locationLookup=location)
```
#My Error
```
Traceback (most recent call last):
  File "./it", line 29, in <module>
    session = auth_session.authenticate(locationLookup=location)
  File "/usr/local/lib/python2.7/site-packages/pogo/api.py", line 182, in authenticate
    }[self.provider](locationLookup=locationLookup, noop=noop)
  File "/usr/local/lib/python2.7/site-packages/pogo/api.py", line 129, in createGoogleSession
    noop=noop
  File "/usr/local/lib/python2.7/site-packages/pogo/api.py", line 95, in createPogoSession
    location = Location(locationLookup, self.geo_key)
  File "/usr/local/lib/python2.7/site-packages/pogo/location.py", line 26, in __init__
    self.latitude, self.longitude, self.altitude = self.setLocation(locationLookup)
  File "/usr/local/lib/python2.7/site-packages/pogo/location.py", line 57, in setLocation
    raise GeneralPogoException('Error in Geo Request')
pogo.custom_exceptions.GeneralPogoException: Error in Geo Request
```

**Comment by dmadisetti** [comment]
Weird. Have you been logging in a lot? Or are you running from an IP where people might be blasting the Google Maps API? Here's the details for Geo Key

https://developers.google.com/maps/documentation/geocoding/get-api-key

**Comment by retep-mathwizard** [comment]
Also, I'm trying to create a bot that spins a pokestop every 5 minutes, but after spinning it, and sleeping for 5 minutes. It drops the connection, and gets an error because too many `API requests`

**Comment by dmadisetti** [comment]
Ahh alright, then that sounds like your issue right there.

It might be better to keep the session going instead of recreate one everytime.

**Comment by retep-mathwizard** [comment]
i'm trying to, why doesn't it let me keep the connection, it disconnects after 5 minutes. I got the Geo Request to work though

**Comment by dmadisetti** [comment]
I'm going to close this guy out then. Feel free to open a new issue if you want to resolve the connection part
