### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by retep-mathwizard** [rubenvereecken/pokemongo-api#103]
My program logs in, gets poke stop, then sleeps for 5 minutes and is supposed to spin it again. This is what happens:
```...
299
300
Line 255,trainer.py- 2016-09-17 18:16:49,065- INFO- Finding Nearest Fort:
Line 235,trainer.py- 2016-09-17 18:16:49,065- INFO- Sorting Nearest Forts:
Line 248,connectionpool.py- 2016-09-17 18:16:49,103- INFO-
Resetting dropped connection : pgorelease.nianticlabs.com
Traceback (most recent call last):
  File "./bot", line 79, in <module>
    trainer.walkAndSpin(fort)
  File "/usr/local/lib/python2.7/site-packages/pogo/trainer.py", line 266, in walkAndSpin
    details = self.session.getFortDetails(fort)
  File "/usr/local/lib/python2.7/site-packages/pogo/session.py", line 134, in getFortDetails
    res = self.wrapAndRequest(payload)
  File "/usr/local/lib/python2.7/site-packages/pogo/session_bare.py", line 304, in wrapAndRequest
    raise PogoRateException(ERROR_RATE)
pogo.custom_exceptions.PogoRateException:Request frequency exceeds rate limit.
```

As you can see, it drops the connection, then cannot reset as the `Request frequency exceeds rate limit.`

**Comment by retep-mathwizard** [comment]
The numbers are from the end of the 5 minute countdown
