### ISSUE TITLE
Connection problem since 13/02/17

### ISSUE THREAD

**Issue by PierreGirardeau** [rubenvereecken/pokemongo-api#112]
Can't connect using the API since 13th February (it seems to be a general problem on other pogo api too) : 

Creating Google session for xxxx
Starting new HTTPS connection (1): android.clients.google.com
Starting new HTTPS connection (1): android.clients.google.com
Limited functionality. No location provided
Starting new HTTPS connection (1): pgorelease.nianticlabs.com
Invalid URL u'https:///rpc': No host supplied
Traceback (most recent call last):
  File "./Loisirs/PokemonGo/AutomaticRenamer/pogo/demo.py", line 709, in <module>
    session = poko_session.authenticate(args.location)
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/api.py", line 149, in authenticate
    }[self.provider](locationLookup=locationLookup, noop=noop)
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/api.py", line 101, in createGoogleSession
    noop=noop
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/api.py", line 71, in createPogoSession
    location
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/session.py", line 62, in __init__
    self.getInventory()
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/session.py", line 216, in getInventory
    self.getProfile()
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/session.py", line 249, in getProfile
    res = self.wrapAndRequest(payload)
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/session.py", line 151, in wrapAndRequest
    res = self.request(self.wrapInRequest(payload, defaults=defaults))
  File "/Users/Pierre/Loisirs/PokemonGo/AutomaticRenamer/pogo/session.py", line 148, in request
    raise GeneralPogoException('Probably server fires.')
custom_exceptions.GeneralPogoException: Probably server fires.

**Comment by olivieretienne** [comment]
Maybe because the legacy api has been closed by Niantic....
