### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by AppliedEllipsis** [rubenvereecken/pokemongo-api#13]
I have all the current dependencies at the exact versions in requirements.txt. I get the following error Python 2.7 Debian. It doesn't matter the arguments given.
```
pokemongo-api/pogo$ ./demo.py
Traceback (most recent call last):
  File "./demo.py", line 8, in <module>
    from api import PokeAuthSession
  File "~/pokemongo-api/pogo/api.py", line 7, in <module>
    from session import PogoSession
  File "~/pokemongo-api/pogo/session.py", line 2, in <module>
    from POGOProtos.Networking.Requests import Request_pb2
  File "~/pokemongo-api/pogo/POGOProtos/Networking/Requests/Request_pb2.py", line 16, in <module>
    from POGOProtos.Networking.Requests import RequestType_pb2 as POGOProtos_dot_Networking_dot_Requests_dot_RequestType__pb2
  File "~/pokemongo-api/pogo/POGOProtos/Networking/Requests/RequestType_pb2.py", line 23, in <module>
    POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

**Comment by therealssj** [comment]
One quick way to fix this is to replace ```syntax='proto3',``` from all the ```_pb2.py``` files.

**Comment by paledrewnem** [comment]
use python3

**Comment by krzys-h** [comment]
Make sure you don't have older versions of protobuf installed anywhere in your system. This helped for me:
```sh
$ sudo apt-get remove python-protobuf
$ pip uninstall protobuf
$ pip install "protobuf==3.0.0b4"
```

**Comment by dmadisetti** [comment]
@AppliedEllipsis Fixed?
