### ISSUE TITLE
Geo Lookups Failing

### ISSUE THREAD

**Issue by jeppybro** [rubenvereecken/pokemongo-api#27]
For the past few hours all geo lookup requests have been failing with the following error regardless of location inputted, long / lat, etc:

```
Line 102,api.py - 2016-07-24 17:35:21,338 - INFO - Creating PTC session for USER
Line 788,connectionpool.py - 2016-07-24 17:35:21,343 - INFO - Starting new HTTPS connection (1): sso.pokemon.com
Traceback (most recent call last):
  File "/home/user/pokemongo-api/pogo/demo.py", line 265, in <module>
    session = poko_session.authenticate(args.location)
  File "/home/user/pokemongo-api/pogo/api.py", line 143, in authenticate
    }[self.provider](locationLookup=locationLookup)
  File "/home/user/pokemongo-api/pogo/api.py", line 135, in createPTCSession
    session=session
  File "/home/user/pokemongo-api/pogo/api.py", line 61, in createPogoSession
    location = Location(locationLookup, self.geo_key)
  File "/home/user/pokemongo-api/pogo/location.py", line 15, in __init__
    self.latitude, self.longitude, self.altitude = self.setLocation(locationLookup)
  File "/home/user/pokemongo-api/pogo/location.py", line 49, in setLocation
    raise GeneralPogoException('Error in Geo Request')
custom_exceptions.GeneralPogoException: Error in Geo Request
```

Anyone able to make successful requests right now?

**Comment by jeppybro** [comment]
Looked to be an issue with the server API responses itself, as it's now working with no changes made on my end.

**Comment by dmadisetti** [comment]
There's also the option to provide a google maps geo IP. You won't get rate limited as hard if you provide one. Should be the -g flag
