### ISSUE TITLE
Error in pokedex.py

### ISSUE THREAD

**Issue by selarep** [rubenvereecken/pokemongo-api#30]
Hello, I don't know why I receive the following error when executing demo.py:
Traceback (most recent call last):
  File "demo.py", line 8, in <module>
    from api import PokeAuthSession
  File "C:\Users\Selarep\Desktop\pokemongo-api-master\pogo\api.py", line 7, in <module>
    from session import PogoSession
  File "C:\Users\Selarep\Desktop\pokemongo-api-master\pogo\session.py", line 22, in <module>
    from inventory import Inventory, items
  File "C:\Users\Selarep\Desktop\pokemongo-api-master\pogo\inventory.py", line 1, in <module>
    from pokedex import pokedex
  File "C:\Users\Selarep\Desktop\pokemongo-api-master\pogo\pokedex.py", line 272, in <module>
    pokedex = Pokedex()
  File "C:\Users\Selarep\Desktop\pokemongo-api-master\pogo\pokedex.py", line 164, in __init__
    super(dict, self).__init__(self)
TypeError: object.__init__() takes no parameters

Can anyone help me, please?

**Comment by dmadisetti** [comment]
Is this on the current master? I did push an unstable version by accident where this was an issue

**Comment by selarep** [comment]
I have fix it changing my Python version from 3.5 to 2.7. Thank you :+1:
