### ISSUE TITLE
Python 3 TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by Paramon** [rubenvereecken/pokemongo-api#33]
```
Traceback (most recent call last):
  File "pogo/demo.py", line 8, in <module>
    from api import PokeAuthSession
  File "pokemongo-api/pogo/api.py", line 7, in <module>
    from session import PogoSession
  File "pokemongo-api/pogo/session.py", line 23, in <module>
    from inventory import Inventory, items
  File "pokemongo-api/pogo/inventory.py", line 1, in <module>
    from pokedex import pokedex
  File "pokemongo-api/pogo/pokedex.py", line 272, in <module>
    pokedex = Pokedex()
  File "pokemongo-api/pogo/pokedex.py", line 164, in __init__
    super(dict, self).__init__(self)
TypeError: object.__init__() takes no parameters
```
We can change   

`super(dict, self).__init__(self)`

to 

`super(dict, self).__init__()`

in:
- pogo/inventory.py
- pogo/pokedex.py

It work as expected in python 2.7 and python 3.5

**Comment by f998601** [comment]
wonderful fix so far, but still getting these errors when running demo.py;
Line 40,demo.py - 2016-07-26 23:01:49,210 - INFO - Finding Nearby Pokemon:
Line 46,demo.py - 2016-07-26 23:01:49,402 - INFO - Current pos: -14.599413, -28.673147
Line 192,demo.py - 2016-07-26 23:01:49,403 - INFO - Finding Nearest Fort:
Line 170,demo.py - 2016-07-26 23:01:49,403 - INFO - Sorting Nearest Forts:
Traceback (most recent call last):
  File "C:\Users\Mstr\Downloads\pokemongo-api-master\pogo\demo.py", line 396, in <module>
    fort = findClosestFort(session)
  File "C:\Users\Mstr\Downloads\pokemongo-api-master\pogo\demo.py", line 193, in findClosestFort
    return sortCloseForts(session)[0]
IndexError: list index out of range

**Comment by obiben** [comment]
This should be fixed as part of https://github.com/rubenvereecken/pokemongo-api/pull/29
you'll get a NoFortFoundException instead, which is somewhat better. What you do with it is up to you... Useful suggestion is to GET OUT OF THE FRACKING OCEAN

**Comment by dmadisetti** [comment]
Fixed
