### ISSUE TITLE
Got an error on first running demo, any idea?

### ISSUE THREAD

**Issue by zyy20853** [rubenvereecken/pokemongo-api#56]
Line 105,api.py - 2016-07-31 00:23:28,953 - INFO - Creating PTC session for zyy20853
Line 788,connectionpool.py - 2016-07-31 00:23:28,965 - INFO - Starting new HTTPS connection (1): sso.pokemon.com
Line 64,api.py - 2016-07-31 00:23:30,261 - INFO - Coordinates: 47.377938 8.5401898 0.0
Traceback (most recent call last):
  File "demo.py", line 385, in <module>
    session = poko_session.authenticate(locationLookup=args.location)
  File "/Users/MD103/Desktop/pokemon/pokemongo-api/pogo/api.py", line 148, in authenticate
    }[self.provider](locationLookup=locationLookup, noop=noop)
  File "/Users/MD103/Desktop/pokemon/pokemongo-api/pogo/api.py", line 139, in createPTCSession
    noop=noop
  File "/Users/MD103/Desktop/pokemon/pokemongo-api/pogo/api.py", line 71, in createPogoSession
    location
  File "/Users/MD103/Desktop/pokemon/pokemongo-api/pogo/session.py", line 57, in __init__
    self.createApiEndpoint(),
  File "/Users/MD103/Desktop/pokemon/pokemongo-api/pogo/session.py", line 85, in createApiEndpoint
    req = self.wrapInRequest(payload)
  File "/Users/MD103/Desktop/pokemon/pokemongo-api/pogo/session.py", line 116, in wrapInRequest
    auth_info=info
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 522, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 453, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 520, in init
    copy.MergeFrom(new_val)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1237, in MergeFrom
    "expected %s got %s." % (cls.__name__, type(msg).__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected AuthTicket got NoneType. for field RequestEnvelope.auth_ticket

**Comment by tsujin** [comment]
Possibly related to Python2.7? I would try running it with Python 3+

**Comment by CognitiveDisson** [comment]
same issue. In method wrapInRequest self.authTicket have value None.

**Comment by dnsBlah** [comment]
just uninstall protobuff
and install the version mentioned in requirements
protobuf==3.0.0b3

**Comment by CognitiveDisson** [comment]
pip show protobuf                                                                                          
---
Metadata-Version: 2.0
Name: protobuf
Version: 3.0.0b3

**Comment by CognitiveDisson** [comment]
`pip install --user -r requirements.txt` - this solved my problem

**Comment by dnsBlah** [comment]
sorry, i assumed you already did :)
please close your issue as well

**Comment by CognitiveDisson** [comment]
Solution has been precisely in the `--user` flag
