### ISSUE TITLE
New Error: list index out of range

### ISSUE THREAD

**Issue by ahmadassaf** [rubenvereecken/pokemongo-api#8]
First, thanks a lot for the clean abstraction and nice code. It was working perfectly up to a point where i started getting

```
Traceback (most recent call last):
  File "demo.py", line 65, in <module>
    logging.info(session.encounterAndCatch(pokemonBest))
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 323, in encounterAndCatch
    return self.catchPokemon(pokemon, pokeball)
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 312, in catchPokemon
    res = self.wrapAndRequest(payload)
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 129, in wrapAndRequest
    if(defaults): self.parseDefault(res)
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 174, in parseDefault
    self.state.settings.ParseFromString(res.returns[4])
  File "/usr/local/lib/python2.7/site-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range
```

**Comment by dmadisetti** [comment]
Branch coming up fixes this. This happens when there's a problem with the request.

What did you envoke to get the breakage?

**Comment by dmadisetti** [comment]
* I say fix- more handles the error.

Those requests should always be set unless something is wrong

**Comment by ahmadassaf** [comment]
thanks for your prompt reply .. this happened suddenly as everything was working fine just before

I tried to do:
```
    # Parse the default responses
    def parseDefault(self, res):
    	if res.returns:
	        self.state.eggs.ParseFromString(res.returns[1])
	        self.state.inventory.ParseFromString(res.returns[2])
	        self.state.badges.ParseFromString(res.returns[3])
	        self.state.settings.ParseFromString(res.returns[4])
```

but i notice that catching is not working when adding this check .. so i believe thats he failing request

**Comment by dmadisetti** [comment]
Pull latest?

**Comment by ahmadassaf** [comment]
just did .. the error now is:

```
Line 192,session.py - 2016-07-23 00:50:05,659 - ERROR - list index out of range
Traceback (most recent call last):
  File "demo.py", line 234, in <module>
    walkAndCatch(session, pokemon)
  File "demo.py", line 66, in walkAndCatch
    logging.info(session.encounterAndCatch(pokemon))
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 470, in encounterAndCatch
    return self.catchPokemon(pokemon, pokeball)
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 339, in catchPokemon
    res = self.wrapAndRequest(payload)
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 143, in wrapAndRequest
    self.parseDefault(res)
  File "/Users/ahmadassaf/Downloads/Applications/pokemongo-api/pogo/session.py", line 193, in parseDefault
    raise GeneralPogoException("Error parsing response. Malformed response")
custom_exceptions.GeneralPogoException: Error parsing response. Malformed response
```

if i log the `res` in the function `parseDefault` i noticed that one `request.response`with status 3  is an empty string, which i believe is the culprit

I like btw the new script and stats !

**Comment by dmadisetti** [comment]
Thanks. Can you post that log?

**Comment by ahmadassaf** [comment]
```
status_code: 3
request_id: 505107160634
returns: ""
```

**Comment by dmadisetti** [comment]
Solved. Was missing pokeballs
